### ISSUE TITLE
Workflow Defaults to First Device Alphabetically; Unable to Select Specific Devices

### ISSUE THREAD

**Issue by AzimsTech** [izer-xyz/openwrt-imagebuilder-action#3]
Currently, the workflow seems to build for the first device in the list of available profiles alphabetically.
The workflow doesn't appear to let you choose for specific devices listed in the profile.

## Steps to Reproduce:

1. Use the template repo: [openwrt-imagebuilder-action-template](https://github.com/izer-xyz/openwrt-imagebuilder-action-template)
2. Modify /config:

```
profile=ramips-mt7621

openwrt_version=23.05.2

packages=luci 

disabled_services=

debug=
```

3. Run workflow 
4. Go to the release section: 
  
Assets 
- adslr_g7-squashfs-sysupgrade.bin
- adslr_g7.manifest
- profiles.json
- sha256sums

**Comment by sinegar** [comment]
In the latest version (v5), I have moved around the paramters. The old `profile` is now `image` and the new `profile` is aligned with the profile in the ImageBuilder. E.g.:
```
image=ramips-mt7621
profile= adslr_g7
openwrt_version=23.05.2
packages=luci 
disabled_services=
debug=
```

(note: previously, I assumed all imageBuilder images were for single profiles… it seems to be the case RPi images)

**Comment by AzimsTech** [comment]
Is it still in progress? [I just tested it](https://github.com/AzimsTech/OpenWrt-imagebuilder/releases/tag/v23.05.2-2), and it doesn't seem right.

**Comment by sinegar** [comment]
should be working but you need to pass the profile parameter to the action (I forgot it in the template): 

```
- name: Build openwrt image
        uses: izer-xyz/openwrt-imagebuilder-action@v5
        with:
          image: ${{ env.image }}
          profile: ${{ env.profile }}
```
